services:
  local-home-devices-mcp:
    image: ghcr.io/paulomac1000/local-home-devices-mcp:latest
    env_file: .env
    network_mode: host
    volumes:
      - local-home-devices-mcp-data:/app/data
    restart: unless-stopped

volumes:
  local-home-devices-mcp-data:
